# Generated by Django 3.2.5 on 2021-07-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_place_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='offer',
            field=models.CharField(max_length=100),
        ),
    ]
