# Generated by Django 3.2.5 on 2022-01-04 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_auto_20210725_0425'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='My Tables',
        ),
    ]
